### ISSUE TITLE
Extract unaligned faces (avatar) is broken in 12/23 commit

### ISSUE THREAD

**Issue by gessyoo** [iperov/DeepFaceLab#536]
THIS IS NOT TECH SUPPORT FOR NEWBIE FAKERS
POST ONLY ISSUES RELATED TO BUGS OR CODE

## Expected behavior:  
run 5) data_dst extract unaligned faces S3FD best GPU (avatar only) to train an avatar model

## Actual behavior

Running 5) data_dst extract unaligned faces outputs misaligned faces.  All faces are tilted sideways.

## Steps to reproduce
 
Run 5) data_dst extract unaligned faces with the latest commit.

Running the same command with a September 2019 version of DFL produces correct alignments.

## Other relevant information

Running prebuilt DFL (Windows 10) with Nvidia 2080ti

**Comment by iperov** [comment]
fixed

**Comment by BostonCs1820** [comment]
I still have the same problem.

I downloaded the newest version (CUDA 26.12).

My picture format is 1080x1080 for both sources. 

Any advice?
